run:
  allow-parallel-runners: true
issues:
  exclude-rules:
    - path: controller #достаточное кол-во контекса на уровне контроллеров
      linters:
        - wrapcheck
    - path: transaction #транзакции прозрачны
      linters:
        - wrapcheck
linters:
  enable-all: true
  disable:
    - goimports #у нас собственные правила форматирования импортов
    - wsl #расставление пробелов очень индивидуально
    - exhaustivestruct #не имеет смысла
    - varnamelen #очень индивидуально (db)
    - exhaustruct #не имеет смысла
    - golint #устарел
    - contextcheck #не имеет смысла
    - gci #у нас собственные правила форматирования импортов
    - gofumpt #у нас собственные правила форматирования импортов
    - nolintlint #Goland все равно форматирует с отступом
    - nlreturn #не всегда имеет смысл
    - godot #не актуально для свагера
    - ifshort #приняли решение, что мы так не пишем if err := ...; err != nil {}
linters-settings:
  funlen:
    lines: 80
  lll:
    line-length: 150
  revive:
    rules:
      - name: var-naming #отключаем Id -> ID
        disabled: true
  stylecheck:
    checks: #отключаем Id -> ID
      - "-ST1000"
      - "-ST1016"
      - "-ST1020"
      - "-ST1021"
      - "-ST1022"
