configServiceAddress:
  ip: 127.0.0.1 # TODO
  port: 9001
grpcOuterAddress:
 #ip: 127.0.0.1
  port: 9xxx # TODO
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9xxx # TODO
moduleName: msp-service # TODO
instanceUuid: ec183598-746a-425f-b5e5-27b7fa8bc6af
