configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
 #ip: 127.0.0.1
  port: 9xxx
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9xxx
moduleName: msp-service
instanceUuid: ec183598-746a-425f-b5e5-27b7fa8bc6af
