// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-10-08 15:53:03.669587506 +0300 MSK m=+19.167429256

package docs

import (
	"github.com/integration-system/isp-lib/v2/docs"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "GNU GPL v3.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/objects/get_all": {
            "post": {
                "description": "{описание метода}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "{название группы методов}"
                ],
                "summary": "{название метода}",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/shared.ObjectDomain"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "shared.ObjectDomain": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "structure.GrpcError": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "errorCode": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = docs.SwaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost:9000",
	BasePath:    "/api/msp-service",
	Schemes:     []string{},
	Title:       "{название сервиса}",
	Description: "{описание сервиса}",
}

func init() {
	docs.InitSwagger(SwaggerInfo, doc)
}
